aws_log_package: "{{ 'awslogs' if ansible_facts['distribution'] == 'Amazon' else 'https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py' if ansible_facts['distribution'] == 'Ubuntu'  }}"
aws_log_configs:
  - { src: "awslogs-service.j2", dest: "/etc/systemd/system/awslogs.service" }
  - { src: "awslogs-config.j2", dest: "/home/{{ deploy_user }}/awslogs.conf" }