deb_php_packages:
  - -curl
  - -fpm
  - -mysql
  - -curl
  - -gd
  - -intl
  - -mbstring
  - -soap
  - -xml
  - -xmlrpc
  - -zip
  - -redis

rpm_php_packages:
  - curl
  - fpm
  - mysqlnd
  - curl
  - gd
  - intl
  - mbstring
  - soap
  - xml
  - xmlrpc
  - zip
  - redis
