- name: Installing CloudWatchAgent
  apt:
    deb: "{{ cloudwatch_package }}"
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Installing CloudWatchAgent
  yum:
    name: "{{ cloudwatch_package }}"
    state: present
  when: ansible_facts['distribution'] == "Amazon"

- name: Copying CoudWatch config
  template:
    src: cloudwatch.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    mode: "644"
    owner: "{{ deploy_user }}"
  notify: Enable Cloudwatch Metrics
