- name: Download and Unpack AWS CLI
  ansible.builtin.unarchive:
    src: "{{ url_aws_cli }}"
    dest: "/opt/"
    validate_certs: true
    remote_src: true
    # owner: "{{ deploy_user }}"
    # group: "{{ deploy_group }}"
    mode: "755"

- name: Install AWS CLI
  changed_when: false
  ansible.builtin.command: "/opt/aws/install"

- name: Check AWS CLI Version
  changed_when: false
  ansible.builtin.command: "/usr/local/bin/aws --version"
