- name: Installing PHP
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: Adding ondrej/php PPA
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php

    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true

    - name: Installing PHP Dependencies
      ansible.builtin.apt:
        name: "{{ php_version ~ item }}"
        state: present
      loop: "{{ deb_php_packages }}"

- name: Instaling PHP
  when: ansible_facts['distribution'] == "Amazon"
  block:
    - name: Installing linux extras
      ansible.builtin.yum:
        name: amazon-linux-extras
        update_cache: true
        state: present

    - name: Enabling PHP extras
      ansible.builtin.command: amazon-linux-extras enable {{ php_version }}
      changed_when: false

    - name: Cleaning metadata
      ansible.builtin.command: yum clean metadata
      changed_when: false

    - name: Installing php{{ php_version[-3:] }}
      ansible.builtin.yum:
        name: "php-{{ item }}"
        state: present
      loop: "{{ rpm_php_packages }}"

- name: Upload new php config file
  when: ansible_facts['os_family'] == "Redhat"
  ansible.builtin.template:
    src: php.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: "644"
  notify: Start PHP-FPM Service

- name: Upload new php config file
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.template:
    src: php.j2
    dest: /etc/php/{{ php_version[-3:] }}/fpm/php.ini
    owner: root
    group: root
    mode: "644"
  notify: Start PHP-FPM Service
