nginx_folder:
  - "{{ efs_mount_path }}"
  - /etc/nginx/nginxconfig.io

nginx_configs:
  - { src: "nginx.j2", dest: "/etc/nginx/nginx.conf" }
  - { src: "website.j2", dest: "/etc/nginx/conf.d/wordpress.conf" }
  - { src: "security.j2", dest: "{{ nginx_folder[1] }}/security.conf" }
  - { src: "general.j2", dest: "{{ nginx_folder[1] }}/general.conf" }
  - { src: "php_fastcgi.j2", dest: "{{ nginx_folder[1] }}/php_fastcgi.conf" }
  - { src: "wordpress.j2", dest: "{{ nginx_folder[1] }}/wordpress.conf" }
  - { src: "w3tc.j2", dest: "{{ nginx_folder[1] }}/w3tc.conf" }

nginx_user: "{{ 'www-data' if ansible_facts['os_family'] == 'Debian' else 'nginx' }}"
