locals {
  region                    = "us-east-1",
  ami_instance_type         = "t2.micro",
  app_ssh_user              = "ubuntu",
  bastion_ssh_user          = "ec2-user",
  block_size                = 30,
  block_type                = "gp3",
  iops_number               = 3000,
  app_ami_name              = "app-ami-gold",
  bastion_ami_name          = "bastion-ami-gold",
  ubuntu_owner_id           = "099720109477",
  amazon_onwer_id           = "amazon",
  ubuntu_root_block_name    = "/dev/sda1",
  amazon_root_block_name    = "/dev/xvda",
  app_ami_location          = "ubuntu/images/hvm-ssd/ubuntu-bionic-*",
  bastion_ami_location      = "amzn2-ami-*",
  delete_termination        = true,
  encrypt                   = false,
  vpc_name                  = "*-vpc-*",
  subnet_name               = "*-private-subnet-1-*",
  sg_name                   = "*-bastion-*",
  app_instance_profile      = "wordpress-app-stg",
  bastion_instance_profile  = "wordpress-bastion-stg"
}
