variable "private_subnets" {}
variable "environment" {}
variable "project" {}
variable "node_class" {}
variable "cluster_number" {}
variable "cache_engine" {}
variable "cache_version" {}
variable "elasticache_paragroup" {}
variable "vpc_id" {}
variable "cache_family" {}
variable "elasticache_sg" {}