- name: Installing Nginx
  apt:
    name: nginx
    state: present

- name: "{{ route53_domain }} Nginx Folders"
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data 
    group: www-data 
    mode: "755"
  loop: "{{ nginx_folder }}"

- name: Main Nginx Config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "644"
  loop: "{{ nginx_configs }}"

- name: "Enabling site {{ route53_domain }}"
  file:
    src: "/etc/nginx/sites-available/{{ route53_domain}}.conf"
    dest: "/etc/nginx/sites-enabled/{{ route53_domain}}.conf"
    owner: root
    group: root
    state: link

- name: Remove The Defaut Website
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Start Nginx Service

