- name: AMI 2 AWS Logs 
  block:
    - name: Installing Cloudwatch Logs
      yum:
        name: "{{ aws_log_package }}"
        state: present
    
    - name: Copying AWS Logs template
      template: 
        src: awslogs-config.j2
        dest: /etc/awslogs/awslogs.conf
        mode: "644"
        owner: root
        group: root
      notify: Enable AWS Logs service 
  when: ansible_facts['distribution'] == 'Amazon'

- name: Ubuntu AWS Logs
  block:
    - name: Get CloudWatch Logs
      get_url:
        url: "{{ aws_log_package }}"
        dest: "/home/{{ deploy_user }}/"
        validate_certs: yes
        owner: "{{ deploy_user }}"
        group: "{{ deploy_group }}"
        mode: "755"

    - name: Copying AWS Logs templates
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "644"
        owner: root
        group: root
      loop: "{{ aws_log_configs }}"

    - name: Installing CloudWatch Logs
      shell: "python awslogs-agent-setup.py -r  {{ aws_region }} -n -c awslogs.conf"
      args:
        chdir: /home/{{ deploy_user }}
      notify: Enable AWS Logs service 
  when: ansible_facts['distribution'] == 'Ubuntu'

